export const ReverseTng = {
  // --- A ---
  account: "acct",
  acquisition: "acq",
  "Active Duty": "AD",
  Additional: "add’l",
  "Administrative Control": "ADCON",
  administration: "admin",
  Advanced: "adv",
  "Advanced Academic Degree": "AAD",
  "Advanced Instructor Course": "AIC",
  "Air Expeditionary Force": "AEF",
  "Air Expeditionary Wing": "AEW",
  "Air Force Instruction": "AFI",
  "Air Force Institute of Technology": "AFIT",
  "Air Force Manual": "AFMAN",
  "Air Force Personnel Center": "AFPC",
  "Air Force Reserve": "AFR",
  "Air Force Research Laboratory": "AFRL",
  "Air Force Specialty Code": "AFSC",
  "Air National Guard": "ANG",
  "Air Operations Center": "AOC",
  "Air Tasking Order or Authority to Operate": "ATO",
  Airman: "Amn",
  "Airman Comprehensive Assessment": "ACA",
  "Airman Leadership School": "ALS",
  "Airman of the Quarter": "AOQ",
  "Airman of the Year": "AOY",
  aircraft: "acft or a/c",
  airfield: "afld",
  airlift: "alft",
  Alternate: "alt",
  "Anti-Satellite": "ASAT",
  Antiterrorism: "AT",
  "Antiterrorism/Force Protection": "AT/FP",
  "Area of Responsibility": "AOR",
  "article 15": "art15",
  "Artificial Intelligence": "AI",
  "As Soon As Possible": "ASAP",
  "award(s)": "awd(s)",
  average: "avg",
  "Absent Without Leave": "AWOL",
  "Action Officer": "AO",
  appointment: "appt",

  // --- B ---
  "Basic Military Training": "BMT",
  "Below-the-Zone": "BTZ",
  between: "b/w",
  building: "bldg",
  "By Name Request": "BNR",

  // --- C ---
  "Calendar Year": "CY",
  capabilities: "capes",
  "Career Field Manger": "CFM",
  "Case Management System": "CMS",
  "center(s)": "ctr(s)",
  certification: "cert",
  certified: "cert’d",
  "Combat Forces Command – SpOC": "CFC",
  combat: "cmbt",
  "Combined Air Ops Center": "CAOC",
  "Combined Force Space Component Command": "CFSCC",
  "Command and Control": "C2",
  "Command, Control, Communications, Computers, Intelligence, Surveillance and Reconnaissance":
    "C4ISR",
  command: "cmd",
  "Commander Directed Investigation": "CDI",
  "Commander’s Critical Information Requirements": "CCIR",
  "Commander’s Inspection Program": "CCIP",
  commander: "cc/cmdr/cdr",
  Commerical: "coml",
  committee: "cmte",
  Communication: "comm",
  "Communications Security": "COMSEC",
  "Community College of the Air Force": "CCAF",
  "Company Grade Officer of the Quarter": "CGOQ",
  "Company Grade Officer of the Year": "CGOY",
  "Concept of Operations": "CONOPS",
  "Concept Plan": "CONPLAN",
  conference: "conf",
  "Congressional Delegation": "CODEL",
  "Contiguous United States": "CONUS",
  "Continuity of Operations": "COOP",
  "Contracting Officer Representative": "COR",
  control: "ctrl",
  "Controlled Unclassified Information": "CUI",
  "Continuous Process Improvement": "CPI",
  "coordinate(d)": "coord/coord’d",
  "Course(s) of Action": "COA",
  "course(s)": "crs/crses",
  "Computer Based Training": "CBT",
  critical: "crit",
  "Change of Command": "CoC",
  "change(s)": "chg(s)",
  checklist: "chklst",
  civilian: "civ",

  // --- D ---
  "Defense Equal Opportunity Climate Survey": "DEOCS",
  "Defense Readiness Reporting System": "DRRS",
  "Defense Travel System": "DTS",
  "defense or definitely": "def",
  Delta: "Del or DEL",
  "Delta Inspection Team": "DIT",
  demonstration: "demo",
  "Department of Air Force Instruction": "DAFI",
  "Department of Force Manual": "DAFMAN",
  department: "dept",
  deputy: "dep",
  detachment: "det",
  "Development Education": "DE",
  "Developmental Special Duty": "DSD",
  "Direct Reporting Unit": "DRU",
  directed: "dir’d",
  director: "dir",
  "Distance Learning": "DL",
  "Distinguished Graduate": "DG",
  "Distinguished Visitor": "DV",
  division: "div",
  "document(s)": "doc(s)",

  // --- E ---
  education: "edu",
  "Electromagnetic Interference": "EMI",
  "Electronic Warfare": "EW",
  "Emergency Management": "EM",
  "Emergency Operations Center": "EOC",
  engineer: "engr",
  enlisted: "enl",
  "Enlisted Performance Report": "EPR",
  equipment: "equip",
  "establish/established": "est/est’d",
  evaluated: "eval’d",
  evaluation: "eval",
  evacuation: "evac",
  exam: "exam",
  "Execution Order": "EXORD",
  executive: "exec",
  "exercise or Exercise": "ex/Ex",

  // --- F ---
  "Field Grade Officer of the Quarter": "FGOQ",
  "Field Grade Officer of the Year": "FGOY",
  "Field Operating Agency": "FOA",
  "Five Eye": "FVEY",
  "Fiscal Year": "FY",
  "Flight Commander": "Flt/CC",
  flight: "flt",
  "Force Protection Conditions": "FPCON",
  "Force Support Squadron": "FSS",
  frequency: "freq",
  "Full Operational Capability": "FOC",
  "Fully Mission Capable": "FMC",
  "Future Years Defense Program": "FYDP",

  // --- G ---
  "General Officer": "GO",
  "Geographically Separated Unit": "GSU",
  "Global Positioning System": "GPS",
  "Government Purchase Card": "GPC",
  "Government Travel Card": "GTC",
  government: "govt",
  GPA: "Grade Point Average",
  "graduate/graduation": "Grad",
  ground: "grnd",
  group: "gp/grp",
  "Group Commander": "Gp/CC",
  "Guardian of the Quarter": "GoQ",
  "Guardian of the Year": "GoY",
  "Guidance & Intent": "G&I",

  // --- H ---
  hardware: "h/w",
  "Hazardous Material": "HAZMAT",
  Headquarters: "HQ",
  "Headquarters Air Force": "HAF",
  helicopter: "helo",
  "Higher Headquarters": "HHQ",
  "high-visibility": "hi-vis",
  hours: "hrs",

  // --- I ---
  "Implementation Plan": "I-Plan",
  "In Accordance With": "IAW",
  "In Order To": "IOT",
  "In Support Of": "ISO",
  "In-or-Above-the-Promotion Zone": "I/APZ",
  "increase/increased": "incr/incr’d",
  "Indications and Warnings": "I&W",
  "Individual Medical Readiness": "IMR",
  "Individual Mobilization Augmentee": "IMA",
  indoctrination: "indoc",
  information: "info",
  "Information Assurance": "IA",
  "Information Technology": "IT",
  "Initial Operational Capability": "IOC",
  Inoperable: "inop",
  "inspection/inspected": "insp/insp’d",
  "Installation Mission Support Center": "IMSC",
  "instruction/instructor": "instr",
  instructed: "instr’d",
  "Integrated Tactical Warning/Attack Assessment": "ITW/AA",
  "Intelligence Community": "IC",
  "Intelligence, Surveillance, and Reconnaissance": "ISR",
  intelligence: "intel",
  "Intercontinental Ballistic Missile": "ICBM",
  "Intermediate Leadership Education": "ILE",
  "International Space Station": "ISS",
  international: "int’l",
  identified: "ID’d/Id’d",

  // --- J ---
  "Joint Planning Team": "JPT",
  "joint services": "Jt",
  "Junior Reserve Officer Training Corps": "JROTC",

  // --- K ---
  "contractor(s)": "ktr(s)",

  // --- L ---
  "leader(s)": "ldr(s)",
  leadership: "ldrshp",
  "Lessons Learned": "LL",
  "Letter of Reprimand": "LOR",
  level: "level",
  "Liaison Officer": "LNO",
  "Limiting Factor": "LIMFAC",
  "Line of Effort": "LOE",

  // --- M ---
  maintenance: "mx",
  managed: "mng’d",
  management: "mgmt",
  manager: "mgr",
  "Master Eligibility List": "MEL",
  maximum: "max",
  medical: "med",
  meeting: "mtg",
  "member(s)": "mbr(s)",
  "Memorandum of Agreement": "MOA",
  "Memorandum of Understanding": "MOU",
  message: "msg",
  MICT: "Management Internal Control Toolset",
  "Military Construction": "MILCON",
  "Military Personnel Data System": "MilPDS",
  military: "mil",
  "Missile Defense Agency": "MDA",
  "Missile Defense": "MD",
  "Missile Warning Center": "MWC",
  "Missile Warning": "MW",
  missile: "msl",
  mission: "msn",
  "modification(s)": "mod(s)",
  months: "mths",
  "Morale, Welfare and Recreation": "MWR",
  mountain: "mtn",
  "Multi-Domain Operations": "MDO",
  "multi-national": "multi-nat’l",

  // --- N ---
  "National Capital Region": "NCR",
  "National Defense Authorization Act": "NDAA",
  national: "nat’l/natl",
  NATO: "North Atlantic Treaty Organization",
  navigation: "nav",
  network: "ntwrk",
  "next-generation": "next-gen",
  "Non-Judicial Punishment": "NJP",
  "Non-Secure Internet Protocol Router Network": "NIPR",
  "Noncommissioned Officer Academy": "NCOA",
  "Noncommissioned Officer in Charge": "NCOIC",
  "Noncommissioned Officer of the Quarter": "NCOQ",
  "Noncommissioned Officer of the Year": "NCOY",
  "Nomination/nominations": "nom(s)",
  Nominee: "nom",
  "Not Mission Capable": "NMC",
  "Numbered Air Force": "NAF",

  // --- O ---
  "object or objective": "obj",
  observation: "obs",
  "of the Quarter": "OTQ",
  "of the Year": "OTY",
  office: "ofc",
  "Officer Training School": "OTS",
  "Officer Performance Report": "OPR",
  "Officer-In-Charge": "OIC",
  officer: "ofcr",
  "Office of the Chief of Space Operations": "OCSO",
  "On-the-Job Training": "OJT",
  "Operating Location": "OL",
  "Operation Plan": "OPLAN",
  "Operational Acceptance": "OA",
  "Operational Control": "OPCON",
  "Operational Readiness Inspection": "ORI",
  "Operations and Maintenance": "O&M",
  "Operations Order": "OPORD",
  "Operations Report": "OPREP",
  "Operations Security": "OPSEC",
  "operation(s)": "op(s)",
  "Orbital Warfare": "OW",
  "Organize, Train & Equip": "OT&E",
  "organization(s)": "org(s)",
  "Outside Contiguous United States": "OCONUS",
  "Overhead Persistent Infrared": "OPIR",
  "Overseas Contingency Operations": "OCO",

  // --- P ---
  "Partially Mission Capable": "PMC",
  passengers: "pax",
  person: "pers",
  "Permanent Change of Assignment": "PCA",
  "Permanent Change of Station": "PCS",
  "Personnel Reliability Assurance Program": "PRAP",
  personnel: "prsnl",
  "Personally Identifiable Information": "PII",
  "package(s)": "pkg(s)",
  "Point of Contact": "POC",
  "Position, Navigation & Timing": "PNT",
  position: "psn",
  preliminary: "prelim",
  preparation: "prep",
  prepared: "prep’d",
  "Preventive Health Assessment": "PHA",
  "Primary Developmental Education": "PDE",
  primary: "pri",
  professional: "pro",
  "Program Objective Memorandum": "POM",
  program: "prgm",
  project: "proj",
  "Professional Military Education": "PME",
  "Protection Level": "PL",

  // --- Q ---
  "Quality Assurance": "QA",
  "Quality Control": "QC",
  "Quality of Life": "QoL",
  quarter: "qtr",
  quarterly: "qtrly",

  // --- R ---
  rating: "rtg",
  ready: "rdy",
  regulation: "reg",
  "report(s)": "rpt(s)",
  representative: "rep",
  "Request For Information": "RFI",
  "requirement(s)": "rqmt(s)",
  "Research and Development": "R&D",
  "Reserved Officer Training Corps": "ROTC",
  residence: "res",
  review: "rvw",
  "Rules of Engagement": "ROE",

  // --- S ---
  "Satellite Communication": "SATCOM",
  satellite: "sat",
  "School of Advanced Air & Space Studies": "SAASS",
  "School of Advanced Warfighting Studies": "SAWS",
  "Science, Technology, Engineering, and Mathmatics": "STEM",
  "Secure Internet Protocol Router Network": "SIPR",
  "Security Classification Guide": "SCG",
  "Self-Assessment Program Manager": "SAPM",
  "Senior Enlisted Leader": "SEL",
  "Senior Executive Service": "SES",
  "Senior Leadership Education": "SLE",
  "Senior Materiel Leader": "SML",
  "Senior Non-Commissioned Officer Academy": "SNCOA",
  "Senior Non-Commissioned Officer of the Quarter": "SNCOQ",
  "Senior Non-Commissioned Officer of the Year": "SNCOY",
  "Senior Rater Identification": "SRID",
  "Senior Rater": "SR",
  senior: "sr",
  "Sensitive Compartmented Information Facility": "SCIF",
  "Sensitive Compartmented Information": "SCI",
  service: "Svc",
  "Sexual Assault Prevention and Response": "SAPR",
  "Sexual Assault Response Coordinator": "SARC",
  simulator: "sim",
  "Situational Awareness": "SA",
  "Situation Report": "SITREP",
  "Space Battle Management": "SBM",
  "Space Command": "USSPACECOM",
  "Space Domain Awareness": "SDA",
  "Space Electronic Warfare": "SEW",
  "Space Force Generation": "SPAFORGEN",
  "Space Force Specialty Code": "SFSC",
  "Space Launch Complex": "SLC",
  "Space Power Discipline": "SPD",
  "Space Situational Awareness": "SSA",
  "Space Surveillance Network": "SSN",
  "Space-based Infrared System": "SBIRS",
  "Space and Missile Systems Center": "SMC",
  space: "spc",
  "Special Access Program": "SAP",
  "Special Operations Command": "USSOCOM",
  "Special Operations Forces": "SOF",
  "Special Technical Operations": "STO",
  "Specialist of the Quarter": "SPCQ",
  "Specialist of the Year": "SPCY",
  "Squadron Commander": "Sq/CC",
  "Squadron Officer School": "SOS",
  squadron: "sq",
  "Staff Assistance Visit": "SAV",
  "Standard Operating Procedure": "SOP",
  "standard(s)": "std(s)",
  "standardization & evaluation": "stan/eval",
  "Strategic Arms Reduction Treaty": "START",
  "student(s)": "stdnt(s)",
  "Subject Matter Expert": "SME",
  Superintendent: "Supt",
  "support/supported": "spt/spt’d",
  "synchronize(d)": "sync/sync’d",
  System: "sys",
  "Systems Program Office": "SPO",
  software: "s/w",

  // --- T ---
  "Tactical Control": "TACON",
  "Tactics, Techniques & Procedures": "TTPs",
  "target(s)": "tgt(s)",
  team: "tm",
  teamwork: "tmwrk",
  "Technical or Tech Order": "TO",
  "technology or technician": "tech",
  "Temporary Duty": "TDY",
  through: "thru",
  "Top Secret": "TS",
  trained: "trn'd",
  training: "trng",
  transportation: "trans",

  // --- U ---
  "Uniform Code of Military Justice": "UCMJ",
  "Unfavorable Information File": "UIF",
  "Unit Compliance Inspection": "UCI",
  "Unit Control Center": "UCC",
  "Unit Deployment Manager": "UDM",
  "Unit Effectiveness Inspection": "UEI",
  "Unit Training Manager": "UTM",
  "Unit Type Code": "UTC",
  "US African Command": "USAFRICOM",
  "US Air Force Weapons School": "USAFWS",
  "US Central Command": "USCENTCOM",
  "US Cyberspace Command": "USCYBERCOM",
  "US European Command": "USEUCOM",
  "US Forces Japan": "USFJ",
  "US Forces Korea": "USFK",
  "US Indian and Pacific Oceans Command": "USINDOPACOM",
  "US Northern Command": "USNORTHCOM",
  "US Southern Command": "USSOUTHCOM",
  "US Strategic Command": "USSTRATCOM",
  "US Transportation Command": "USTRANSCOM",
  "US Special Operations Command": "USSOCOM",
  "US Space Command": "USSPACECOM",
  "United States": "US",
  "United States Air Force Academy": "USAFA",
  "United States Army": "USA",
  "United States Government": "USG",
  "United States Marine Corps": "USMC",
  "United States Navy": "USN",
  "United States Space Force": "USSF",

  // --- V ---
  versus: "vs",
  "Video Teleconference": "VTC",
  "volunteer/volunteered": "vol/vol’d",

  // --- W ---
  "weapon(s)": "wpn(s)",
  "Weapon(s) of Mass Destruction": "WMD",
  "Weapons Instructor Course": "WIC",
  weather: "wx",
  week: "wk",
  weekly: "wkly",
  wg: "wing",
  "White House": "WH",
  "Wing Commander": "Wg/CC",
  with: "w/",
  within: "w/in",
  without: "w/o",

  // --- Y ---
  year: "yr",
  yearly: "yrly",
};
