export const TngDict = {
  // --- 1 ---
  "1st Sgt": "First Sergeant",

  // --- A ---
  AAD: "Advanced Academic Degree",
  acct: "account",
  "acft or a/c": "aircraft",
  acq: "acquisition",
  ACA: "Airman Comprehensive Assessment",
  AD: "Active Duty",
  "add’l": "additional",
  ADCON: "Administrative Control",
  admin: "administration",
  adv: "advanced",
  AEF: "Air Expeditionary Force",
  AEW: "Air Expeditionary Wing",
  AFI: "Air Force Instruction",
  afld: "airfield",
  AFIT: "Air Force Institute of Technology",
  AFMAN: "Air Force Manual",
  AFPC: "Air Force Personnel Center",
  AFR: "Air Force Reserve",
  AFRL: "Air Force Research Laboratory",
  AFSC: "Air Force Specialty Code",
  AI: "Artificial Intelligence",
  AIC: "Advanced Instructor Course",
  alft: "airlift",
  ALS: "Airman Leadership School",
  alt: "alternate",
  Amn: "Airman",
  ANG: "Air National Guard",
  AO: "Action Officer",
  AOC: "Air Operations Center",
  AOQ: "Airman of the Quarter",
  AOR: "Area of Responsibility",
  AOY: "Airman of the Year",
  appt: "appointment",
  art15: "article 15",
  ASAP: "As Soon As Possible",
  ASAT: "Anti-Satellite",
  AT: "Antiterrorism",
  "AT/FP": "Antiterrorism/Force Protection",
  ATO: "Air Tasking Order or Authority to Operate",
  avg: "average",
  awd: "award(s)",
  AWOL: "Absent Without Leave",

  // --- B ---
  "b/w": "between",
  bldg: "building",
  BMT: "Basic Military Training",
  BNR: "By Name Request",
  BTZ: "Below-the-Zone",

  // --- C ---
  C2: "Command and Control",
  C4ISR:
    "Command, Control, Communications, Computers, Intelligence, Surveillance and Reconnaissance",
  CAOC: "Combined Air Ops Center",
  capes: "capabilities",
  CBT: "Computer Based Training",
  CCAF: "Community College of the Air Force",
  "cc/cmdr/cdr": "commander",
  CCIP: "Commander’s Inspection Program",
  CCIR: "Commander’s Critical Information Requirements",
  CDI: "Commander Directed Investigation",
  CFC: "Combat Forces Command – SpOC",
  CFM: "Career Field Manger",
  CFSCC: "Combined Force Space Component Command",
  CGOQ: "Company Grade Officer of the Quarter",
  CGOY: "Company Grade Officer of the Year",
  cert: "certification",
  "cert’d": "certified",
  "chg(s)": "change(s)",
  chklst: "checklist",
  civ: "civilian",
  CMS: "Case Management System",
  cmbt: "combat",
  cmd: "command",
  cmte: "committee",
  COA: "Course(s) of Action",
  CoC: "Change of Command",
  CODEL: "Congressional Delegation",
  coml: "commerical",
  comm: "communication",
  COMSEC: "Communications Security",
  conf: "conference",
  CONOPS: "Concept of Operations",
  CONPLAN: "Concept Plan",
  CONUS: "Contiguous United States",
  COOP: "Continuity of Operations",
  coord: "coordinate(d)",
  "coord’d": "coordinate(d)",
  COR: "Contracting Officer Representative",
  CPI: "Continuous Process Improvement",
  crit: "critical",
  "crs/crses": "course(s)",
  "ctr(s)": "center(s)",
  ctrl: "control",
  CUI: "Controlled Unclassified Information",
  CY: "Calendar Year",

  // --- D ---
  DAFI: "Department of Air Force Instruction",
  DAFMAN: "Department of Force Manual",
  DE: "Development Education",
  def: "defense or definitely",
  DEOCS: "Defense Equal Opportunity Climate Survey",
  "Del or DEL": "Delta",
  demo: "demonstration",
  dep: "deputy",
  dept: "department",
  det: "detachment",
  DG: "Distinguished Graduate",
  dir: "director",
  "dir’d": "directed",
  DIT: "Delta Inspection Team",
  div: "division",
  DL: "Distance Learning",
  "doc(s)": "document(s)",
  DRRS: "Defense Readiness Reporting System",
  DRU: "Direct Reporting Unit",
  DSD: "Developmental Special Duty",
  DTS: "Defense Travel System",
  DV: "Distinguished Visitor",

  // --- E ---
  edu: "education",
  EM: "Emergency Management",
  EMI: "Electromagnetic Interference",
  EOC: "Emergency Operations Center",
  engr: "engineer",
  enl: "enlisted",
  EPR: "Enlisted Performance Report",
  equip: "equipment",
  est: "establish/established",
  "est’d": "establish/established",
  evac: "evacuation",
  eval: "evaluation",
  "eval’d": "evaluated",
  "ex/Ex": "exercise or Exercise",
  exam: "exam",
  exec: "executive",
  EW: "Electronic Warfare",
  EXORD: "Execution Order",

  // --- F ---
  FGOQ: "Field Grade Officer of the Quarter",
  FGOY: "Field Grade Officer of the Year",
  flt: "flight",
  "Flt/CC": "Flight Commander",
  FMC: "Fully Mission Capable",
  FOA: "Field Operating Agency",
  FOC: "Full Operational Capability",
  FPCON: "Force Protection Conditions",
  freq: "frequency",
  FSS: "Force Support Squadron",
  FVEY: "Five Eye",
  FY: "Fiscal Year",
  FYDP: "Future Years Defense Program",

  // --- G ---
  "G&I": "Guidance & Intent",
  GO: "General Officer",
  GoQ: "Guardian of the Quarter",
  GoY: "Guardian of the Year",
  govt: "government",
  GPA: "Grade Point Average",
  GPC: "Government Purchase Card",
  GPS: "Global Positioning System",
  "Gp/CC": "Group Commander",
  "gp/grp": "group",
  Grad: "graduate/graduation",
  grnd: "ground",
  GSU: "Geographically Separated Unit",
  GTC: "Government Travel Card",

  // --- H ---
  HAF: "Headquarters Air Force",
  HAZMAT: "Hazardous Material",
  HC: "Chaplain Corps",
  "h/w": "hardware",
  helo: "helicopter",
  HHQ: "Higher Headquarters",
  "hi-vis": "high-visibility",
  HQ: "Headquarters",
  hrs: "hours",

  // --- I ---
  "I&W": "Indications and Warnings",
  "I/APZ": "In-or-Above-the-Promotion Zone",
  IA: "Information Assurance",
  IAW: "In Accordance With",
  IC: "Intelligence Community",
  ICBM: "Intercontinental Ballistic Missile",
  "ID’d/Id’d": "identified",
  ILE: "Intermediate Leadership Education",
  IMA: "Individual Mobilization Augmentee",
  IMR: "Individual Medical Readiness",
  IMSC: "Installation Mission Support Center",
  incr: "increase/increased",
  "incr’d": "increase/increased",
  IOC: "Initial Operational Capability",
  indoc: "indoctrination",
  info: "information",
  inop: "inoperable",
  insp: "inspection/inspected",
  "insp’d": "inspection/inspected",
  instr: "instruction/instructor",
  "instr’d": "instructed",
  intel: "intelligence",
  "int’l": "international",
  IOT: "In Order To",
  "I-Plan": "Implementation Plan",
  ISO: "In Support Of",
  ISR: "Intelligence, Surveillance, and Reconnaissance",
  ISS: "International Space Station",
  IT: "Information Technology",
  "ITW/AA": "Integrated Tactical Warning/Attack Assessment",

  // --- J ---
  JPT: "Joint Planning Team",
  JROTC: "Junior Reserve Officer Training Corps",
  Jt: "joint services",

  // --- K ---
  "ktr(s)": "contractor(s)",

  // --- L ---
  "ldr(s)": "leader(s)",
  ldrshp: "leadership",
  level: "level",
  LIMFAC: "Limiting Factor",
  LL: "Lessons Learned",
  LNO: "Liaison Officer",
  LOE: "Line of Effort",
  LOR: "Letter of Reprimand",

  // --- M ---
  max: "maximum",
  MD: "Missile Defense",
  MDA: "Missile Defense Agency",
  MDO: "Multi-Domain Operations",
  MEL: "Master Eligibility List",
  "mbr(s)": "member(s)",
  med: "medical",
  mgmt: "management",
  mgr: "manager",
  MICT: "Management Internal Control Toolset",
  MILCON: "Military Construction",
  mil: "military",
  MilPDS: "Military Personnel Data System",
  mng: "managed",
  "mng’d": "managed",
  MOA: "Memorandum of Agreement",
  "mod(s)": "modification(s)",
  MOU: "Memorandum of Understanding",
  msg: "message",
  msl: "missile",
  msn: "mission",
  mtg: "meeting",
  mths: "months",
  mtn: "mountain",
  "multi-nat’l": "multi-national",
  MW: "Missile Warning",
  MWC: "Missile Warning Center",
  MWR: "Morale, Welfare and Recreation",
  mx: "maintenance",

  // --- N ---
  NAF: "Numbered Air Force",
  "nat’l/natl": "national",
  NATO: "North Atlantic Treaty Organization",
  nav: "navigation",
  NCOA: "Noncommissioned Officer Academy",
  NCOIC: "Noncommissioned Officer in Charge",
  NCOQ: "Noncommissioned Officer of the Quarter",
  NCOY: "Noncommissioned Officer of the Year",
  NCR: "National Capital Region",
  NDAA: "National Defense Authorization Act",
  "next-gen": "next-generation",
  NIPR: "Non-Secure Internet Protocol Router Network",
  NJP: "Non-Judicial Punishment",
  NMC: "Not Mission Capable",
  nom: "nominee",
  "nom(s)": "nomination/nominations",
  ntwrk: "network",

  // --- O ---
  "O&M": "Operations and Maintenance",
  OA: "Operational Acceptance",
  obj: "object or objective",
  obs: "observation",
  OCO: "Overseas Contingency Operations",
  OCONUS: "Outside Contiguous United States",
  OCSO: "Office of the Chief of Space Operations",
  ofc: "office",
  ofcr: "officer",
  OIC: "Officer-In-Charge",
  OJT: "On-the-Job Training",
  OL: "Operating Location",
  OPCON: "Operational Control",
  OPIR: "Overhead Persistent Infrared",
  OPLAN: "Operation Plan",
  OPORD: "Operations Order",
  op: "operation(s)",
  "op(s)": "operation(s)",
  OPR: "Officer Performance Report",
  OPREP: "Operations Report",
  OPSEC: "Operations Security",
  ORI: "Operational Readiness Inspection",
  "org(s)": "organization(s)",
  "OT&E": "Organize, Train & Equip",
  OTS: "Officer Training School",
  OTQ: "of the Quarter",
  OTY: "of the Year",
  OW: "Orbital Warfare",

  // --- P ---
  pax: "passengers",
  PCA: "Permanent Change of Assignment",
  PCS: "Permanent Change of Station",
  PDE: "Primary Developmental Education",
  pers: "person",
  PHA: "Preventive Health Assessment",
  PII: "Personally Identifiable Information",
  "pkg(s)": "package(s)",
  PL: "Protection Level",
  PMC: "Partially Mission Capable",
  PME: "Professional Military Education",
  PNT: "Position, Navigation & Timing",
  POC: "Point of Contact",
  POM: "Program Objective Memorandum",
  prelim: "preliminary",
  prep: "preparation",
  "prep’d": "prepared",
  prgm: "program",
  pri: "primary",
  pro: "professional",
  proj: "project",
  PRAP: "Personnel Reliability Assurance Program",
  prsnl: "personnel",
  psn: "position",

  // --- Q ---
  QA: "Quality Assurance",
  QC: "Quality Control",
  QoL: "Quality of Life",
  qtr: "quarter",
  qtrly: "quarterly",

  // --- R ---
  "R&D": "Research and Development",
  rdy: "ready",
  reg: "regulation",
  rep: "representative",
  res: "residence",
  RFI: "Request For Information",
  ROE: "Rules of Engagement",
  rpt: "report(s)",
  "rpt(s)": "report(s)",
  rqmt: "requirement(s)",
  "rqmt(s)": "requirement(s)",
  ROTC: "Reserved Officer Training Corps",
  rtg: "rating",
  rvw: "review",

  // --- S ---
  SA: "Situational Awareness",
  SAASS: "School of Advanced Air & Space Studies",
  SAP: "Special Access Program",
  SAPM: "Self-Assessment Program Manager",
  SAPR: "Sexual Assault Prevention and Response",
  SARC: "Sexual Assault Response Coordinator",
  sat: "satellite",
  SATCOM: "Satellite Communication",
  SAV: "Staff Assistance Visit",
  SAWS: "School of Advanced Warfighting Studies",
  SBIRS: "Space-based Infrared System",
  SBM: "Space Battle Management",
  SCG: "Security Classification Guide",
  SCI: "Sensitive Compartmented Information",
  SCIF: "Sensitive Compartmented Information Facility",
  SDA: "Space Domain Awareness",
  SLE: "Senior Leadership Education",
  SEL: "Senior Enlisted Leader",
  SES: "Senior Executive Service",
  SEW: "Space Electronic Warfare",
  SFSC: "Space Force Specialty Code",
  sim: "simulator",
  SIPR: "Secure Internet Protocol Router Network",
  SITREP: "Situation Report",
  SLC: "Space Launch Complex",
  SMC: "Space and Missile Systems Center",
  SME: "Subject Matter Expert",
  SML: "Senior Materiel Leader",
  SNCOA: "Senior Non-Commissioned Officer Academy",
  SNCOQ: "Senior Non-Commissioned Officer of the Quarter",
  SNCOY: "Senior Non-Commissioned Officer of the Year",
  SOF: "Special Operations Forces",
  SOP: "Standard Operating Procedure",
  SOS: "Squadron Officer School",
  SPAFORGEN: "Space Force Generation",
  SPD: "Space Power Discipline",
  spc: "space",
  SPO: "Systems Program Office",
  SPCQ: "Specialist of the Quarter",
  SPCY: "Specialist of the Year",
  sr: "senior",
  SR: "Senior Rater",
  SRID: "Senior Rater Identification",
  SSA: "Space Situational Awareness",
  SSN: "Space Surveillance Network",
  spt: "support/supported",
  "spt/spt’d": "support/supported",
  sq: "squadron",
  "Sq/CC": "Squadron Commander",
  "stan/eval": "standardization & evaluation",
  std: "standard(s)",
  "std(s)": "standard(s)",
  "stdnt(s)": "student(s)",
  START: "Strategic Arms Reduction Treaty",
  STEM: "Science, Technology, Engineering, and Mathmatics",
  STO: "Special Technical Operations",
  Supt: "Superintendent",
  Svc: "service",
  "s/w": "software",
  sync: "synchronize(d)",
  "sync/sync’d": "synchronize(d)",
  sys: "system",

  // --- T ---
  TACON: "Tactical Control",
  TDY: "Temporary Duty",
  tech: "technology or technician",
  tgt: "target(s)",
  "tgt(s)": "target(s)",
  thru: "through",
  tm: "team",
  tmwrk: "teamwork",
  TO: "Technical or Tech Order",
  trans: "transportation",
  "trn'd": "trained",
  trng: "training",
  TS: "Top Secret",
  TTPs: "Tactics, Techniques & Procedures",

  // --- U ---
  UCC: "Unit Control Center",
  UCI: "Unit Compliance Inspection",
  UCMJ: "Uniform Code of Military Justice",
  UDM: "Unit Deployment Manager",
  UEI: "Unit Effectiveness Inspection",
  UIF: "Unfavorable Information File",
  US: "United States",
  USA: "United States Army",
  USAFA: "United States Air Force Academy",
  USAFRICOM: "US African Command",
  USAFWS: "US Air Force Weapons School",
  USCENTCOM: "US Central Command",
  USCYBERCOM: "US Cyberspace Command",
  USEUCOM: "US European Command",
  USFJ: "US Forces Japan",
  USFK: "US Forces Korea",
  USG: "United States Government",
  USINDOPACOM: "US Indian and Pacific Oceans Command",
  USMC: "United States Marine Corps",
  USN: "United States Navy",
  USNORTHCOM: "US Northern Command",
  USSF: "United States Space Force",
  USSOCOM: "US Special Operations Command",
  USSOUTHCOM: "US Southern Command",
  USSPACECOM: "US Space Command",
  USSTRATCOM: "US Strategic Command",
  USTRANSCOM: "US Transportation Command",
  UTC: "Unit Type Code",
  UTM: "Unit Training Manager",

  // --- V ---
  VTC: "Video Teleconference",
  vol: "volunteer/volunteered",
  "vol/vol’d": "volunteer/volunteered",
  vs: "versus",

  // --- W ---
  "w/": "with",
  "w/in": "within",
  "w/o": "without",
  wg: "wing",
  "Wg/CC": "Wing Commander",
  WH: "White House",
  WIC: "Weapons Instructor Course",
  wk: "week",
  wkly: "weekly",
  WMD: "Weapon(s) of Mass Destruction",
  wpn: "weapon(s)",
  "wpn(s)": "weapon(s)",
  wx: "weather",

  // --- Y ---
  yr: "year",
  yrly: "yearly",
};
